# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'HZPlaceHolder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'HZPlaceHolder/PlaceHolderView', :path => '../'
  pod 'HZPlaceHolder/Refresh', :path => '../'
  pod 'MJRefresh'

end
